-- AlterEnum
ALTER TYPE "AnnouncementAudience" ADD VALUE IF NOT EXISTS 'DEPARTMENT_HEAD_ONLY';
ALTER TYPE "AnnouncementAudience" ADD VALUE IF NOT EXISTS 'TEACHER_DEPARTMENT_HEAD';
ALTER TYPE "AnnouncementAudience" ADD VALUE IF NOT EXISTS 'STUDENT_DEPARTMENT_HEAD';
ALTER TYPE "AnnouncementAudience" ADD VALUE IF NOT EXISTS 'ALL';
