BEGIN;

ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "titleFr" TEXT;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "descriptionFr" TEXT;

ALTER TABLE "Program" ADD COLUMN IF NOT EXISTS "degreeLevelFr" TEXT;
ALTER TABLE "Program" ADD COLUMN IF NOT EXISTS "fieldOfStudyFr" TEXT;

COMMIT;
